### ISSUE TITLE
Access to Plug.Conn in a processing pipeline

### ISSUE THREAD

**Issue by h8** [absinthe-graphql/absinthe_plug#109]
Hi! I'm trying to find a way of modifying http response returned by Absinthe Plug depending on results of a query (mutation) execution. For example, I want to put a new cookie into the response if mutation resolver has successfully returned some value (User model). I'm trying to build such workflow: 

1. Login mutation resolver should return a User model; 
2. Middleware function (which works after resolver) should found this model and add some additional data into a resolution context, for example – add user ID;
3. Custom phase handler added into a pipeline (for example, after Absinthe.Phase.Document.Result) should look for that additional data and (if found) – generate JWT token and put it into a response as a cookie. 

In such case I don't mix transport level with the logic and all transport-related stuff encapsulated in a Pipeline Phase.

Is this workflow even possible? Now I have several issues:
1. I return modified Resolution (with custom data added into the context) from a field middleware function, but this data never appears in a context object of a Phase handler;
2. Phase handlers also don't have an access to a Plug.Conn instance, so I can't modify it. 

Maybe there is another way of doing this and I'm doing something wrong. Please help.

**Comment by benwilson512** [comment]
Hey @h8, sorry for the long delay in the reply. I agree that it isn't super easy at the moment. My first thought was that you could create a wrapping plug, but the conn doesn't ever actually contain the response body so that won't work.

It may be that we need to add a `before_send` callback to Absinthe.Plug that passes in the conn, the graphql response, and maybe the whole blueprint.

**Comment by h8** [comment]
Thanks for answer, @benwilson512! What do you think about ability of returning modified context of Resolution object in order to path some metadata from field middleware to, for example, before_send callback that you've mentioned? This could be allowed only for mutations.

**Comment by benwilson512** [comment]
I could consider passing in the entire blueprint, and then you could lookup the context from within it.

**Comment by bruce** [comment]
@benwilson512 @h8 Is there absinthe_plug changes needed here? Should we close this issue and/or come up with some concrete next steps?

**Comment by lexun** [comment]
I've been looking for something similar. Would love to have an exclusively GraphQL API, but also have the option to use sessions instead of tokens. Just need a way to affect the Plug.Conn from inside a login mutation.

**Comment by benwilson512** [comment]
Pulling an example from the PR docs, how does this look:

  ## Before Send
  If you need to set a value (like a cookie) on the connection after resolution
  but before values are sent to the client, use the `:before_send` option:
  ```
  plug Absinthe.Plug,
    schema: MyApp.Schema,
    before_send: {__MODULE__, :absinthe_before_send}

  def absinthe_before_send(conn, %Absinthe.Blueprint{} = blueprint}) do
    auth_token = blueprint.execution.context[:auth_token]
    put_session(conn, :auth_token, auth_token)
  end
  def absinthe_before_send(conn, _) do
    conn
  end
  ```

To get a `current_user_id` in the context you can just use middleware after your login mutation

```
resolve fn args, _ ->
  case authenticate(args) do
    {:ok, token} -> {:ok, %{token: token}}
    error -> error
  end
end
middleware fn resolution, _ ->
  with %{value: %{token: token}} <- resolution do
    Map.update!(resolution, :context, fn ctx ->
      Map.put(ctx, :auth_token, token)
    end)
  end
end)
```

**Comment by h8** [comment]
Many thanks for this! When it will be in the release?

**Comment by benwilson512** [comment]
Later today, mostly wanted to make sure that it looked like this would work for everyone.

**Comment by tmepple** [comment]
I was wondering if you use sessions (typically using cookies) to store the auth token like in the above example if you open yourself up to CSRF attacks on subsequent query/mutation POST requests?  If so how should it be mitigated?  It's simple enough to store a CSRF token in the page and submit it as a `x-csrf-token` header in the query/mutation for validation but not sure if it's required.  Also not sure exactly how to deal with token staleness/refresh/reuse issues if needed in multiple queries/mutations.

**Comment by benwilson512** [comment]
@tmepple let's direct "how to" style questions for the forum or slack please.
