### ISSUE TITLE
DocumentProvider.Compiled macro defines fxn with wrong args

### ISSUE THREAD

**Issue by shamshirz** [absinthe-graphql/absinthe_plug#112]
Relatively new to the library, and trying to create my first compiled doc provider.

**What happened:**
1. Tried defining a module with `use Absinthe.Plug.DocumentProvider.Compiled`
2. Wrote a test to use the provided doc
3. Ran into this error
  ```
  Attempted function clauses (showing 1 out of 1):
           defp do_process(%{params: %{"id" => document_key}} = request)
  ```
4. Thought, "that is strange", looks like the macro defines two function clauses for `do_process`

**Conclusion**
The second definition is expecting two args, but it will only every have 1. Currently looks like `do_process(request, _)` and it should look like `do_process(request)`.

That could be intentional, sorry if it is! Just a little confused about it.

https://github.com/absinthe-graphql/absinthe_plug/blob/664b5690ee0d94e59a494be70a8462e8583283e3/lib/absinthe/plug/document_provider/compiled.ex#L80

**Comment by bruce** [comment]
Sorry it's taken so long to address this; will try to take a look at this as we work on finalizing changes for the v1.4 release this week.

**Comment by shamshirz** [comment]
Woop, thanks!
