### ISSUE TITLE
Unable to upload file via mutation using Apollo

### ISSUE THREAD

**Issue by richeterre** [absinthe-graphql/absinthe_plug#114]
I'm trying to upload a picture to a Phoenix application from my React Native app, using a GraphQL mutation that sends the picture as an argument. Unfortunately, Absinthe throws an error when receiving the mutation, possibly because of a malformed request.

Server: `absinthe 1.4.0-rc.2`, `absinthe_plug 1.4.0-rc.0`
Client: `react-native 0.49.3`, `apollo-upload-client 5.1.1`

In my `schema.ex`:

```
field :update_profile_picture, type: :string do
  arg :picture, non_null(:upload)

  resolve fn args, _ ->
    {:ok, "success"}
  end
end
```

My mutation:

```
mutation UpdateProfilePicture($picture: Upload!) {
  updateProfilePicture(picture: $picture)
}
```

and I run it from the client like this:

```
const image = … // my image object
const file = new ReactNativeFile({
  uri: image.path,
  type: 'image/jpeg',
  name: 'test.jpg'
})

this.props.updateProfilePicture({
  variables: {
    picture: file,
  },
})
```

After submitting, I see the following in my server logs:

```
[error] #PID<0.10558.0> running MyApp.Endpoint terminated
Server: api.myapp.local:4000 (http)
Request: POST /graphql
** (exit) an exception was raised:
    ** (BadMapError) expected a map, got: {"operationName", "UpdateProfilePicture"}
        (elixir) lib/map.ex:424: Map.get({"operationName", "UpdateProfilePicture"}, "query", "")
        lib/absinthe/plug/request/query.ex:131: Absinthe.Plug.Request.Query.extract_raw_document/2
        lib/absinthe/plug/request/query.ex:51: Absinthe.Plug.Request.Query.parse/3
        (elixir) lib/enum.ex:1259: anonymous fn/3 in Enum.map/2
        (stdlib) lists.erl:1263: :lists.foldl/3
        (elixir) lib/enum.ex:1828: Enum.map/2
        lib/absinthe/plug/request.ex:54: Absinthe.Plug.Request.build_request/4
        lib/absinthe/plug/request.ex:49: Absinthe.Plug.Request.parse/2
        lib/absinthe/plug.ex:217: Absinthe.Plug.execute/2
        lib/absinthe/plug.ex:155: Absinthe.Plug.call/2
        (phoenix) lib/phoenix/router/route.ex:161: Phoenix.Router.Route.forward/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (myapp) lib/myapp/endpoint.ex:1: MyApp.Endpoint.plug_builder_call/2
        (myapp) lib/plug/debugger.ex:99: MyApp.Endpoint."call (overridable 3)"/2
        (myapp) lib/myapp/endpoint.ex:1: MyApp.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/richeterre/Code/MyApp/myapp-phoenix/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Is this something that could be fixed by making minor adjustments on the client side, as suggested by @confiks in https://github.com/absinthe-graphql/absinthe_plug/pull/98? As I understand it, `apollo-upload-client` has sparked the interest of the Apollo core team and might become more "official" in the future: https://github.com/apollographql/apollo/issues/65

**Comment by richeterre** [comment]
Update – I got it to work (🎉) using a different library: https://github.com/labtwentyfive/apollo-absinthe-upload-client

That library wasn't compatible with React Native out of the box, but the only difference is that in addition to scanning variables for `File` and `FileList` objects, it also detects the custom `ReactNativeFile` type, which is just a lightweight object holding URI, name and type of the file, and appends those to the multipart form as well.

My plan is to file a PR to the above library that adds React Native support.

@benwilson512, the "odd error message" I posted was probably caused by the differences in format between Absinthe and Apollo Server, the latter of which is targeted by `apollo-upload-client`, right?

**Comment by benwilson512** [comment]
Maybe, I'd be very curious to see what the raw HTTP body actually looked like (with the upload contents elided). The part it's failing on is strange.

**Comment by richeterre** [comment]
I added some logging to my client middleware and the request looks indeed quite strange:

<img width="471" alt="screen shot 2017-10-23 at 17 00 07" src="https://user-images.githubusercontent.com/555663/31896344-ca23288a-b813-11e7-9676-3c10f0abb81d.png">

when compared to other queries and mutations in my client, whose `query` attribute is not a string, but an object holding `definitions`, `kind` and `loc`.

**Comment by bruce** [comment]
@benwilson512 @richeterre Is this an issue with absinthe_plug, or has this transitioned into clear Apollo territory? Should we perhaps close this as an issue and take it up as an ongoing Slack discussion---or do we see Absinthe changes needed here?

**Comment by tmjoen** [comment]
@richeterre I'm currently having the same problem. I tried the `apollo-absinthe-upload-client` you linked a bit up but it is giving me problems when I have arrays as variables.

I wrote a little more about it here:

https://github.com/labtwentyfive/apollo-absinthe-upload-client/issues/1

Whatever it is doing when traversing the variables it is making Absinthe read my arrays as maps instead of lists.

**Comment by clentfort** [comment]
Hi y'all,

author of [labtwentyfive/apollo-absinthe-upload-client][1] here. We created the library because [jaydenseric/apollo-upload-client][2] does not work with Absinthe, because Absinthe expects the query under the fieldname `query`, while `apollo-upload-server` expects the query under the fieldname `operations`.

[1]: https://github.com/labtwentyfive/apollo-absinthe-upload-client
[2]: https://github.com/jaydenseric/apollo-upload-client

**Comment by clentfort** [comment]
@richeterre react-native-support was not a priority for us, but we would gladly accept a PR.

**Comment by richeterre** [comment]
Hi @clentfort, I was considering a PR but given my severe lack of both time and TypeScript experience, I made this slightly hacky fork: https://github.com/labtwentyfive/apollo-absinthe-upload-client/compare/master...richeterre:master

Basically the only thing needed to make it work with React Native is to add a custom file type for React Native files (see https://github.com/jaydenseric/apollo-upload-client#react-native) and change the `isFile` function to accept this type as well. It works like a charm.

Should I open a PR and you help convert it to proper TS without having to disable linting rules etc?

**Comment by bruce** [comment]
Thanks for your work on this, @clentfort & @richeterre.

CCing @mgtitimoli and @tlvenn — we may look at a future official Absinthe package(s) to help support uploads down the road.

@richeterre / @clentfort, let's take the PR planning for labtwentyfive/apollo-absinthe-upload-client over to that repo, please.

**Comment by richeterre** [comment]
Good point @bruce, will do. Looking forward to (maybe) getting first-class Absinthe support for this! Would be yet another reason for me to wholeheartedly recommend it to fellow "full-stack" devs 😊

**Comment by tlvenn** [comment]
I see that apollo-upload-client is supporting Apollo Link now. It would probably be a good idea to revisit the library given we also support Apollo Link.

**Comment by tlvenn** [comment]
As for supporting multi part form fields as specified there: https://github.com/jaydenseric/graphql-multipart-request-spec , that's probably something we can handle with a plug so by the time it hits absinthe side of things, it would be in the expected format.

**Comment by benwilson512** [comment]
Glad to see there is a specification now, I'll see if we can get this into Absinthe.Plug nice.y

**Comment by jeroenvisser101** [comment]
@benwilson512 so if someone was going to be implementing this, is the approach to build a plug that converts the spec-proposed way to the way Absinthe is currently able to read it? (if I understand correctly, that is what @tlvenn was suggesting)

**Comment by jeroenvisser101** [comment]
I've taken a stab at this but the spec suggests sending the value as null and then looking it up in the 'map' param, which seems to cause errors in the case where a argument is 'required', like specified [here](https://github.com/absinthe-graphql/absinthe/blob/master/lib/absinthe/phase/document/arguments/parse.ex#L34-L36). I can't think of an easy way to circumvent this, any thoughts? cc @benwilson512 @tlvenn

**Comment by benwilson512** [comment]
Yea that occurred to me as well. I am not a big fan of using null to mean the opposite of null.

**Comment by jeroenvisser101** [comment]
@benwilson512 me neither, but suggesting a change in spec seems unlikely to be accepted. Can we 'ban' the use of non_null type for the :upload scalar and introduce required option that is then passed to the scalar when parsing?

**Comment by jeroenvisser101** [comment]
We could choose to move away from the spec, and I could just fork this upload-client and make it work with the way we handle files right now.

**Comment by benwilson512** [comment]
Hey @jeroenvisser101. I think the most important spec to keep in mind here is the GraphQL spec itself, and I think forbidding the use of `non_null` or using `null` in the way that this upload spec does violates certainly the spirit of the GraphQL spec.

I'm going to lobby the upload spec to see if we can get a change to happen there. If that fails we'll look at other options.

**Comment by jeroenvisser101** [comment]
Sure, let me know, here to help :)

**Comment by jeroenvisser101** [comment]
Also, the spec is v2.0.0-alphaX so we might be able to twist it a little

**Comment by benwilson512** [comment]
https://github.com/jaydenseric/graphql-multipart-request-spec/issues/4

**Comment by richeterre** [comment]
Having Absinthe support file uploads from Apollo out of the box would be a fantastic selling point. Seems like https://github.com/jaydenseric/apollo-upload-client has [a lot more momentum](https://github.com/jaydenseric/apollo-upload-client/releases) than the other libraries I could find, plus a wider audience as it also works with React Native.

@benwilson512, what's your take on this after your conversation with jaydenseric? Sadly I didn't understand half of it 😬

**Comment by benwilson512** [comment]
I'm not really a big fan of the format, so I don't think it's likely to get first class support within Absinthe.Plug, at least without broader adoption.

It is however totally doable to add support for it via a third party library, so I'd be happy to help guide someone in that direction should they be interested in doing so.

**Comment by jeroenvisser101** [comment]
@richeterre I wanted to implement the format but we ended up changing the apollo-upload-client library to support the format that Absinthe is using, we made it available here: https://www.npmjs.com/package/@novistore/apollo-upload-client. Usage is the same, but it will send it slightly differently so it matches what Absinthe is used to seeing, which is a format that we at Novistore prefer.

**Comment by dmarkow** [comment]
@jeroenvisser101 This works great, thank you! The github repo tied to the package doesn't have any of the changes though? (I had to look at the source of the npm package to see what was changed).

@benwilson512 I may be willing to tackle this with a little direction on where to start with a 3rd party lib... (I've extended Absinthe with some authorization middleware, but nothing fancier than that, and I haven't done anything with Absinthe.Plugin yet).

**Comment by jeroenvisser101** [comment]
@dmarkow I'll push them tonight, seems like they were committed but not pushed.

**Comment by jeroenvisser101** [comment]
@dmarkow I've pushed both repo's to GitHub, [extract-files](https://github.com/novistore/extract-files) and [apollo-upload-client](https://github.com/novistore/apollo-upload-client).

**Comment by richeterre** [comment]
For anyone coming across this thread: If you want to use apollo-upload-client with Absinthe, you can also use my forked package: https://www.npmjs.com/package/@richeterre/apollo-upload-client

It's very similar to @jeroenvisser101's (thanks for the great input 🙏), but its internal modifications are somewhat simpler; for instance, it didn't require forking [extract-files](https://github.com/jaydenseric/extract-files) at all. The original [apollo-upload-client](https://github.com/jaydenseric/apollo-upload-client) is moving at high speed, and I personally hope the community will converge on a common standard soon so we don't need to keep these in sync forever. 😉 

You can find the repo [here](https://github.com/richeterre/apollo-upload-client).

**Comment by jeroenvisser101** [comment]
If anyone beats me to it, it should be added [here](https://github.com/absinthe-graphql/absinthe/blob/master/guides/client/apollo.md)

**Comment by jeroenvisser101** [comment]
We might as well write the whole guide then
