### ISSUE TITLE
Render GraphiQL

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe_plug#12]
As does express-graphql. Here's the source: https://github.com/graphql/express-graphql/blob/master/src/renderGraphiQL.js

**Comment by benwilson512** [comment]
So this is the default response if the content type is application/html right?

This should be off by default in production?

**Comment by bruce** [comment]
> So this is the default response if the content type is application/html right?

Whatever express-graphql does, and it can't interfere with any HTML bits the host app is serving, of course.

> This should be off by default in production?

Yes, and on by default in development, and overridable on/off for either. This may differ from express-graphql a bit -- I think theres is just an option you pass in, and it's falsey by default.

**Comment by bruce** [comment]
Also, ninja-adding an interface by default probably warrants a bump to v1.1.

**Comment by benwilson512** [comment]
Current plans:

This should be a separate plug. We'll need to refactor out common functionality from the existing plug because it'll be used in both cases. This will make it easy to configure it along side regular graphql functionality in variety of ways. One could forward to it from a router etc.

**Comment by bruce** [comment]
Resolved by #15
