### ISSUE TITLE
Update fork of graphql-playground

### ISSUE THREAD

**Issue by craig-day** [absinthe-graphql/absinthe_plug#127]
Sorry to open this here, but I'm not sure where the best place is and since this is where graphql-playground gets consumed I figured I would start here. 

Can https://github.com/absinthe-graphql/graphql-playground be updated to pull in latest changes from upstream? I had some fixes in there I would love to be able to use. 

Thanks!

**Comment by tlvenn** [comment]
Hi @craig-day, this is definitely the right place. I have created a PR with an updated playground version including your latest commit in their repo.

**Comment by craig-day** [comment]
Thanks!

**Comment by craig-day** [comment]
@tlvenn or @benwilson512 any chance we can get a tagged release that pulls in these changes?

**Comment by benwilson512** [comment]
v1.4.1 is now on hex!
