### ISSUE TITLE
Custom error handeling

### ISSUE THREAD

**Issue by stankec** [absinthe-graphql/absinthe_plug#138]
Hi!

I'm experiencing issues while using `Absinthe.Plug` in conjunction with Sentry (an error logging service). I can't get Sentry to report an error (neither through a Plug nor through `:error_logger`).

I've managed to find a [similar issue on their issue tracker](https://github.com/getsentry/sentry-elixir/issues/229) and after some digging figured out that [this line](https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug.ex#L267) causes the same problem as the one outlined in the issue.

__My question is, is there a way to implement custom error handling with this library?__ Or o way to get the described integration to work?

**Comment by benwilson512** [comment]
I'm a bit unclear on what it is that you're looking for here. Are you trying to get GraphQL errors sent to sentry?

**Comment by stankec** [comment]
> Are you trying to get GraphQL errors sent to sentry?
I am.

**Comment by benwilson512** [comment]
Arguably your best bet here is to add a custom phase. Absinthe works by having a big list of modules, and then passing a graphql document through functions on each of those modules. Each module does some part of the execution process.

The idea here is that you can just add an additional module to the end of the list that will do whatever sentry stuff you want.

A phase can be added via the `pipeline` option to the plug invocation:

```
plug Absinthe.Plug,
  schema: MyApp.Schema,
  pipeline: {__MODULE__, :absinthe_pipeline}

def absinthe_pipeline(config, opts) do
  config
  |> Absinthe.Plug.default_pipeline(opts)
  |> Absinthe.Pipeline.insert_after(Absinthe.Phase.Document.Result, MyApp.SentryErrors)
end
```

So in `absinthe_pipeline/2` we build the default pipeline, and then add in `MyApp.SentryErrors` after the result is built. Let's see what that would look like:

```
defmodule MyApp.SentryErrors do
  def run(blueprint, _) do
    errors = blueprint.result.errors
    # do whatever with errors here
    {:ok, blueprint}
  end
end
```

Hopefully that gets you off to the right start.

**Comment by stankec** [comment]
@benwilson512 Seems like I can solve this problem that way. Thanks for the explanation.
