### ISSUE TITLE
Update deps to Absinthe 1.1.0

### ISSUE THREAD

**Issue by skosch** [absinthe-graphql/absinthe_plug#14]
... please :)

**Comment by bruce** [comment]
We'll actually point this as v1.1.1, which we'll be releasing momentarily for a bugfix. Thanks!

**Comment by skosch** [comment]
That was fast. Thanks!

**Comment by bruce** [comment]
As was noted in Slack (and @skosch, I know you already know this, but in case anyone else sees this...), for the moment use `override: true` on your `absinthe` dependency in your `mix.exs`. This will be updated as soon as we release this next (imminent-ish) version of the plug.

**Comment by benwilson512** [comment]
Fixed in #15
