### ISSUE TITLE
Be able to compile queries loaded from textfile

### ISSUE THREAD

**Issue by sweco-semtne** [absinthe-graphql/absinthe_plug#140]
The current Compiled DocumentProvider macro does not work if you want to provide queries from files and set the key in the Document Provider. 

I would like to be able to use the provide macro like this: 

```
provide %{
    "key" -> File.read!("query.txt")
}
```

**Comment by benwilson512** [comment]
To follow on: The current issue is that `provide` is a macro, so consequently it takes AST. The `File.read!` function isn't actually executed at this point, so the contents aren't read.
