### ISSUE TITLE
Absinthe.Plug.GraphiQL ignores the `:default_url` option for the GraphQL Playground interface

### ISSUE THREAD

**Issue by smaximov** [absinthe-graphql/absinthe_plug#148]
[The docs](https://hexdocs.pm/absinthe_plug/Absinthe.Plug.GraphiQL.html#module-default-url) say that the `:default_url` option applies to the advanced interface and the GraphQL Playground:

> ## Default URL
>
> You can also optionally set the default URL to be used for sending the queries to. This only applies to the advanced interface (GraphiQL Workspace) and the GraphQL Playground.

Consider this setup:

``` elixir
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :api do
    plug :accepts, ["json"]
    plug BlogWeb.Context
  end

  scope "/api" do
    pipe_through :api

    forward "/graphiql", Absinthe.Plug.GraphiQL,
      schema: BlogWeb.Schema,
      interface: :playground, # works with :advanced
      default_url: {__MODULE__, :graphql_default_url}

    forward "/", Absinthe.Plug,
      schema: BlogWeb.Schema
  end

  def graphql_default_url, do: BlogWeb.Endpoint.url() <> "/api"
end
```

The URL returned from `graphql_default_url` is ignored when the GraphQL Playground is enabled (it works with the advanced interface though). Clearing local storage doesn't help.

**Comment by benwilson512** [comment]
Can you include the version of Absinthe.Plug you're using?

**Comment by smaximov** [comment]
@benwilson512, I use `v1.4.0` (it's from [absinthe_tutorial](https://github.com/absinthe-graphql/absinthe_tutorial)).

**Comment by benwilson512** [comment]
If you do `mix deps absinthe_plug` what do you get? if it's 1.4.0 please make sure to update.

**Comment by smaximov** [comment]
It was locked on 1.4.0, so I updated it to the latest version (1.4.2):

``` bash
$ mix deps | grep absinthe_plug
* absinthe_plug (Hex package) (mix)
  locked at 1.4.2 (absinthe_plug) 01bf16f0
```

I recompiled the project, cleared local storage and reloaded the playground, the issue still persists: it uses `http://localhost:4000/api/graphiql` instead of `http://localhost:4000/api` by default and if I set the endpoint to `http://localhost:4000/api` then reload the page it will revert the endpoint to the default value.

**Comment by sinwailam193** [comment]
Currently, the release 1.4.2 does not have the change that fixes this
```
<%= if default_url do %>
   options.endpoint = <%= default_url %>;
 <% end %>
```
So I would just install via git
```
{:absinthe_plug, git: "https://github.com/absinthe-graphql/absinthe_plug.git"}
```
to get the latest changes, and this would fix the problem you have

**Comment by smaximov** [comment]
@sinwailam193 thanks for the info, I tried Git master and looks like it's fixed now.

**Comment by benwilson512** [comment]
Just released AbsinthePlug 1.4.3 which should include this.

**Comment by acrogenesis** [comment]
This seems to be broken in the advanced interface now

**Comment by acrogenesis** [comment]
I can confirm if I set the interface to playground it sets correctly but when not specifying or using :advanced it doesn't apply:

```
get("/graphiql", Absinthe.Plug.GraphiQL,
      schema: AppWeb.Schema,
      socket: AppWeb.UserSocket,
      default_url: {__MODULE__, :graphql_default_url}
    )
```
```
def graphql_default_url, do: AppWeb.Endpoint.url() <> "/api"
```

**Comment by jeregrine** [comment]
Can confirm on absinthe_plug 1.4.7 default url is not being set for the advanced mode.
