### ISSUE TITLE
Support crunching json payload

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe_plug#154]
I stumbled upon this library:
> https://github.com/banterfm/graphql-crunch

It seems like a useful thing to do and it would be great if we could support the crunching side of this lib with a Plug.

**Comment by benwilson512** [comment]
This is already supported for all intents and purposes right? Just supply a custom JSON codec.

**Comment by tlvenn** [comment]
Ya good point, it can be plugged in already. I was wondering if it's something we would want to support outside of the box ?

**Comment by tlvenn** [comment]
Fair enough ;)
