### ISSUE TITLE
Breaks on plug 1.5.1

### ISSUE THREAD

**Issue by archSeer** [absinthe-graphql/absinthe_plug#157]
On 1.5.1, it seems to parse the queries with newlines included:

```
{"operationName":null,"variables":{},"query":"{\n  events {\n    id\n    title: name\n   __typename\n    }\n    __typename\n  }\n}\n"}
```

which fails with `message: syntax error before: "\"operationName\""`

**Comment by benwilson512** [comment]
I don't think this is a plug or absinthe error, this looks more like the content type of the request isn't set correctly. Can you confirm you're sending the requests with content type `application/json` ?

**Comment by archSeer** [comment]
I narrowed it down to the plug 1.5.1 upgrade, It works fine on 1.5.0, where the debug log is also formatted differently:

```
---                                                                                                                                                                                                         {                                                                                                                                                                                                             events {
    id
    title: name
    __typename                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
---
```

And yes, request is marked as `content-type: application/json; charset=utf-8`.

From what I can tell, [1.5.1 bumped Cowboy](https://github.com/elixir-plug/plug/commit/e34c10004c13a1f1f7c627388086acc19bdb18dd) so request parsing might have changed or something.

**Comment by benwilson512** [comment]
Interesting.

Are you sure this isn't a bug in plug? are you able to investigate this further?

**Comment by archSeer** [comment]
Seems to be working again on plug 1.6.
