### ISSUE TITLE
Replacing middleware breaks GraphiQL discovery

### ISSUE THREAD

**Issue by exlee** [absinthe-graphql/absinthe_plug#159]
I have JSON data that I'm matching to query. Due to this keys I have to match against string, not atom keys.

After a bit of searching, I've found https://github.com/absinthe-graphql/absinthe/issues/268, which proposes swapping middleware (just the same as `Absinthe.Schema.replace_default` example). While this solution works, it breaks GraphiQL schema discovery. 

I tried removing _all the schemas_ and it still breaks.

Exact code that is causing the problem:
```elixir
  def middleware(middleware, field, object) do
    new_middleware = {Absinthe.Middleware.MapGet, to_string(field.identifier)}

    middleware
    |> Absinthe.Schema.replace_default(new_middleware, field, object)
  end

```
Versions:

- Absinthe: 1.4.12
- Absinthe.Ecto: 0.1.3
- Absinthe.Plug: 1.4.4

It looks like the data is stripped when providing GraphiQL with discovery data. Some of the truncated output below.

(Note, I'm not sure Absinthe.Plug is the best way to call the issue, but IMHO this is more GraphiQL problem than Absinthe in general, because queries work).

```
{"data":{"__schema":{"types":[{"possibleTypes":null,"name":null,"kind":"OBJECT","interfaces":[],"inputFields":null,"fields":[{"type":{"ofType":null,"name":null,"kind":"SCALAR"},"name":"active","isDeprecated":false,"description":null,"deprecationReason":null,"args":[]},{"type":{"ofType":null,"name":null,"kind":"SCALAR"},"name":"firstName","isDeprecated":false,"description":null,"deprecationReason":null,"args":[]},{"type":{"ofType":null,"name":null,"kind":"SCALAR"},"name":"lastLogin","isDeprecated":false,"description":null,"deprecationReason":null,"args":[]},{"type":{"ofType":null,"name":null,"kind":"SCALAR"},"name":"lastName","isDeprecated":false,"description":null,"deprecationReason":null,"args":[]},{"type":{"ofType":{"ofType":null,"name":null,"kind":"OBJECT"},"name":null,"kind":"LIST"},"name":"loginEmails","isDeprecated":false,"description":null,"deprecationReason":null,"args":[]},{"type":{"ofType":{"ofType":null,"name":null,"kind":"SCALAR"},"name":null,"kind":"NON_NULL"},"name":"uuid"
```

**Comment by benwilson512** [comment]
Ah interesting, the introspection types are supposed to be exempted from the `def middleware` callback, but perhaps I messed that up.

**Comment by exlee** [comment]
I resolved this by adding gate for Introspection types:

```elixir
def middleware(current_middleware, %{__reference__: %{module: Absinthe.Type.BuiltIns.Introspection}}, object), do: current_middleware
```
Probably this should be put in documentation for replace_default :)

**Comment by benwilson512** [comment]
Nah this is a bug in Absinthe, people should never need to do that, I'll create an issue.
