### ISSUE TITLE
Type Upload import error in Elixir 1.7

### ISSUE THREAD

**Issue by Apelsinka223** [absinthe-graphql/absinthe_plug#162]
Hi, thanks for package. Got error after update up to Elixir 1.7:

```
File :upload is not defined in your schema.
  
  Types must exist if referenced.

    lib/absinthe/schema.ex:271: Absinthe.Schema.__after_compile__/2
    (stdlib) lists.erl:1263: :lists.foldl/3
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```
Schema:
```
 import_types Absinthe.Plug.Types
 ...
 input_object :object do
    field :file, non_null(:upload)
    ...
 end
```

Temporary fixed this with adding `scalar :upload` from `lib/absinthe/plug/types.ex:48` directly to schema

**Comment by Apelsinka223** [comment]
Solved with `rm -rf _build`, sorry 😄

**Comment by roostercrab** [comment]
Wait, what did you rm -rf _build?

**Comment by benwilson512** [comment]
@roostercrab that command is usually run in the root of your Elixir project to force a recompilation from scratch.

**Comment by roostercrab** [comment]
That's what I figured, but it didn't do anything when I ran it until I took out the _ and changed to the directory with the build folder in it, but then I didn't know how to get it to re"build" that folder...
