### ISSUE TITLE
Should pull default adapter from application env

### ISSUE THREAD

**Issue by 1player** [absinthe-graphql/absinthe_plug#166]
The guide on https://hexdocs.pm/absinthe/Absinthe.Adapter.html states, quote:

```
To set an adapter, you can set an application configuration value:

config :absinthe,
  adapter: YourApp.Adapter.TheAdapterName
```

absinthe_plug should use this value as default, if no adapter is manually configured on the plug. Currently it defaults to Absinthe.Adapter.LanguageConventions

Keep in mind that Absinthe itself seems to ignore this value, there's a related bug report at https://github.com/absinthe-graphql/absinthe/issues/587

**Comment by benwilson512** [comment]
PR welcome.

**Comment by benwilson512** [comment]
Closed via https://github.com/absinthe-graphql/absinthe/issues/587#issuecomment-484909287
