### ISSUE TITLE
Apply before_send callback on error as well ?

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe_plug#168]
Hi,

I am leveraging :before_send callback option to capture absinthe result in order to provide idempotent mutations. I was kinda expecting that this callback would be called no matter what but unfortunately, at the moment, it's only being called on the happy path:

```
defp run_query(query, conn ,conn_info, config) do
    %{document: document, pipeline: pipeline} = Request.Query.add_pipeline(query, conn_info, config)
    case Absinthe.Pipeline.run(document, pipeline) do
      {:ok, %{result: result} = bp, _} ->
        conn = apply_before_send(conn, [bp], config)
        {conn, {:ok, result}}
      val ->
        {conn, val}
    end
  end
```

Could we change it so that we actually call it all the time @benwilson512 ? It would guarantee that my logic can handle an unexpected error within Absinthe, for example, when the resolver is returning an error that is not following the expected shape.

**Comment by benwilson512** [comment]
@tlvenn yeah we can have it show up in the error case too, although notably exceptions within a resolver or similar will still bubble up and get handled by Plug.

**Comment by binaryseed** [comment]
Closing this issue since it's gone stale. Please feel free to re-open if this particular feature is still needed...

**Comment by eprothro** [comment]
We ran into this as well. We're using a `before_send` callback to pull the root operation from the resolution context and put it into the conn for use by a logging plug. Works great in the happy path, but isn't called when there is an exception.

**Comment by opsb** [comment]
We have rate limiting running within absinth (custom phases) and want to return a 429 http status code. We currently return an error which means a 500 is returned. If `before_send` was available for errors then we could add the status code there.

Seems like the most flexible thing to do would be to move the `before_send` call to the end of the `call` implementation https://github.com/absinthe-graphql/absinthe_plug/blob/v1.5.8/lib/absinthe/plug.ex#L320.
