### ISSUE TITLE
Batch query mismatch between apollo and absinthe

### ISSUE THREAD

**Issue by qqdanielqq** [absinthe-graphql/absinthe_plug#169]
Following on from our conversation on the slack channel, we are encountering a mis match between apollo making batch queries and the response that absinthe gives us.

Response from Apollo Server
```[{"data":{"__schema":{"queryType":{"name":"RootQuery"}}}},{"data":{"__schema":{"queryType":{"description":""}}}}]```

Response from Absinthe
```[{"operationName":"_fooexample","payload":{"extensions": ...,"data": ... }}]```

Attached is a small demo project that demonstrates this:

https://github.com/kirill-kruchkov/apollo-client-batch-n-state-issue-demo

If you can provide any help with this that would be great!!

**Comment by thomasbrus** [comment]
If you're using Apollo Client in combination with `BatchHttpLink` you can simply workaround the issue as follows:

```js
const absintheAfterwareLink = new ApolloLink((operation, forward) => {
  return forward(operation).map(response => {
    // Also see https://github.com/absinthe-graphql/absinthe_plug/issues/89#issuecomment-307845018
    return { ...response, data: response.payload.data };
  });
});

let link = ApolloLink.from([
  absintheAfterwareLink,

  // ...,

  new BatchHttpLink({
    batchMax: 100,
    batchInterval: 10,
  }),
]);

let cache = new InMemoryCache();

export default new ApolloClient({ link, cache });
```

**Comment by binaryseed** [comment]
Addressed in https://github.com/absinthe-graphql/absinthe_plug/pull/237
