### ISSUE TITLE
GraphiQL integration with phoenix returns an error response

### ISSUE THREAD

**Issue by telnicky** [absinthe-graphql/absinthe_plug#17]
Following the documentation and inserting the following in the router:
```
get "/graphiql", Absinthe.Plug.GraphiQL, schema: MyApp.Schema
```
When I visit the url "/graphiql" the response I receive is `No query document supplied`. What I expected to see was the graphiql UI here.

After providing a query the graphiql UI renders, however the response doesn't seem quite right. It returns what appears to be the `graphiql.html.eex` file.

**Comment by benwilson512** [comment]
Hey there this is indeed a bug, seems a last minute validation change messed us up, I need something closer to a full integration test don't I. Will get a fix up here shortly.

**Comment by dre1080** [comment]
@benwilson512 you should look at the [plug_graphql](https://github.com/graphql-elixir/plug_graphql/blob/master/lib/graphql/plug/graphiql.ex) implementation

**Comment by benwilson512** [comment]
This isn't a problem with the general implementation, but rather an issue that cropped up when I had the GraphiQL plug share query validation with the regular plug. I should be able to get to it tonight.

**Comment by benwilson512** [comment]
Fixed on master.
