### ISSUE TITLE
Debugging complex GraphQL queries with shortlinks to GraphiQL

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/absinthe_plug#170]
> https://nilsnh.no/2018/08/04/debugging-complex-graphql-queries-with-shortlinks-to-graphiql/

That seems like an interesting and useful idea

**Comment by binaryseed** [comment]
This is interesting, but isn't something that fits the goal of `Absinthe.Plug` which is to provide the standard HTTP transport mechanism for GraphQL.

This could be built as an external package leveraging the `telemetry` instrumentation that is built into Absinthe!
