### ISSUE TITLE
Question mark (?) in field key causes GraphiQL errors

### ISSUE THREAD

**Issue by elbow-jason** [absinthe-graphql/absinthe_plug#185]
### Environment

* Elixir version (elixir -v):

```
Erlang/OTP 21 [erts-10.0.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.1 (compiled with Erlang/OTP 21)
```

* Absinthe version (mix deps | grep absinthe):

```
* absinthe 1.4.13 (Hex package) (mix)
  locked at 1.4.13 (absinthe) 81eb2ff4
* absinthe_plug 1.4.5 (Hex package) (mix)
  locked at 1.4.5 (absinthe_plug) f63d52a7
```

* Client Framework and version (Relay, Apollo, etc):

`GraphiQL` via `absinthe_plug`

### Expected behavior

Upon page initialization GraphiQL should have searchable docs and a `RootQueryType` to click on.

### Actual behavior

Upon page load the results section is displaying errors and there is no schema available.

<img width="1669" alt="screen shot 2018-10-18 at 10 45 25 pm" src="https://user-images.githubusercontent.com/4923601/47199764-058bca00-d328-11e8-9238-e35d2597f7da.png">

The error text for progeny's sake:
```
assertValidName@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:13341
defineFieldMap/<@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:19:27858
defineFieldMap@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:19:27835
[256]</exports.GraphQLObjectType</e.prototype.getFields@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:20:2217
typeMapReducer@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2759
typeMapReducer@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2283
typeMapReducer/<@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2906
typeMapReducer@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:2773
e@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:6282
buildClientSchema@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:29467
value/<@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:14:12748
```

### Code

```elixir
defmodule ServiceDiscoveryWeb.Schema.ServiceTypes do
  use Absinthe.Schema.Notation

  object :service do
    field :id, :id
    field :name, :string
    field :uri, :string
    field :requires_auth?, :boolean
    field :permissions_level, :string
  end
end
```

### FIx action

Removing the `?` from the `:requires_auth?` field fixes this issue:

```elixir
defmodule ServiceDiscoveryWeb.Schema.ServiceTypes do
  use Absinthe.Schema.Notation

  object :service do
    field :id, :id
    field :name, :string
    field :uri, :string
    field :requires_auth, :boolean
    field :permissions_level, :string
  end
end
```
<img width="1651" alt="screen shot 2018-10-18 at 10 50 39 pm" src="https://user-images.githubusercontent.com/4923601/47199836-64514380-d328-11e8-8860-0afbff9f6e32.png">

**Comment by elbow-jason** [comment]
To my surprise the `assertValidName` of `assertValidName@https://cdn.jsdelivr.net/npm/graphiql-workspace@1.1.4/graphiql-workspace.min.js:21:13341` actually helped me figure out what was wrong.

**Comment by elbow-jason** [comment]
If this is already documented or if this is a reopening of an issue then I apologize. I was having no luck with my google fu.

**Comment by benwilson512** [comment]
@bruce do you know if a question mark is a valid identifier?

**Comment by binaryseed** [comment]
`?` is not valid...

https://graphql.github.io/graphql-spec/draft/#Name

`/[_A-Za-z][_0-9A-Za-z]*/`

**Comment by bottlenecked** [comment]
Hi all, just musing here. Absinthe is now converting snake_case to camelCase. But a question mark at the end could be either an is_* or a has_* or anything that can be answered in a binary manner. So this type of auto conversion will probably not  work. Simply removing the question mark at the end could work but perhaps there are edge cases with similarly named fields on the models. @benwilson512 do you think that this should be handled inside Absinthe or leave it up to users to make an explicit mapping/resolution in their fields?

**Comment by binaryseed** [comment]
The only reasonable default behavior for Absinthe is to raise and error when compiling the schema, anything else is invalid GraphQL.

If a server wants to break the GraphQL contract, it's possible to remove this phase from the schema compilation pipeline:

`Absinthe.Phase.Schema.Validation.NamesMustBeValid`
