### ISSUE TITLE
GraphiQL plug's socket url is set to an empty string by default

### ISSUE THREAD

**Issue by rmoorman** [absinthe-graphql/absinthe_plug#187]
I was following along the craft graphql apis in elixir with absinthe book working on my own implementation instead of using the provided example code and it seems that using the `socket` option for the plug (set to the project's usersocket just as the book suggested) does not work for discovery of the socket url.

This behaviour seems to be caused by the logic here
https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/graphiql.ex#L415
and https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/graphiql/graphiql.html.eex#L69
which therefore can render subscriptions unusable within at least the simple graphiql client.

The wsUrl ends up as `''` in the template instead of defaulting to the value `ws://localhost:4000/socket` that is found in the template (because a string containing a pair of single quotes `"''"` is not falsy) as far as I could infer by reading through the code a bit.

Looking at the issues reported so far I didn't see something similar coming up which is the reason that I am reporting this as an issue.

**Comment by rmoorman** [comment]
I will try to look into it in more detail when I finished the book. Meanwhile setting the `socket_url` option directly to `ws://localhost:4000/socket` does work.

**Comment by benwilson512** [comment]
What version of Phoenix / Absinthe are you on?

**Comment by rmoorman** [comment]
@benwilson512 I am on
* phoenix 1.4.0-rc.0
* absinthe 1.4.13
* absinthe_phoenix 1.4.3
* absinthe_plug 1.4.5
* Elixir 1.7.3 (compiled with Erlang/OTP 19)

**Comment by benwilson512** [comment]
Right, Absinthe Plug hasn't had a release yet that works with the phoenix 1.4 rc. I'll try to get one out today since I think the PR is already in master.

**Comment by rmoorman** [comment]
@benwilson512 I just tried master and I can confirm that the functionality is now working out of the box again by just adding the socket module to the plug options.

**Comment by rmoorman** [comment]
@benwilson512 thank you for taking the time to look into this 👍
