### ISSUE TITLE
Websocket / subscription support is broken on workspace.

### ISSUE THREAD

**Issue by JonRowe** [absinthe-graphql/absinthe_plug#189]
Using Absinthe 1.5.0-alpha1, and `49e7d12ab522f50e62cfef97950c2cf574b1be4e` of this lib, the workspace interface won't send subscription queries over the websocket. It connects ok (you can see control frames, it might just be for the live reload though?) but it sends subscription queries as HTTP.

Simple and playground interfaces are unaffected.

**Comment by binaryseed** [comment]
Closing this issues since our path forward is removing the various GraphiQL implementations from `Absinthe.Plug`.
