### ISSUE TITLE
No longer logging Runtime errors in development with plug_cowboy 2.0

### ISSUE THREAD

**Issue by samginn** [absinthe-graphql/absinthe_plug#196]
Hi,

When upgrading to phoenix 1.4, I upgraded to Cowboy 2 as well as specified in the upgrade docs of phoenix to support HTTP2. When doing this, however, Absinthe no longer is logging runtime errors to the console when they happen. This is only affecting Absinthe; errors within phoenix controllers are logged just fine.

For example, if I place `:error = :ok` somewhere in one of my resolvers and trigger that resolver, the console will not display any error, just the :info log of the request, but not the :error log with the stacktrace of where it went wrong (obviously, this makes debugging quite hard).

This occurs when using (in mix.exs):

```
{:plug_cowboy, "~> 2.0"},
```

If, however, I downgrade this to 1.0, then errors within Absinthe's resolvers get logged just fine and I have no issue:

```
{:plug_cowboy, "~> 1.0"},
```

I am using absinthe_plug 1.4.6.

Does Absinthe not support Cowboy 2?

Thanks!

**Comment by benwilson512** [comment]
Absinthe doesn't know anything about cowboy, regardless of version. Can you provide a project that shows this behavior?

**Comment by binaryseed** [comment]
Closing for now, this doesn't look related to Absinthe
