### ISSUE TITLE
It requires Poison as primary JSON decoder

### ISSUE THREAD

**Issue by ffimnsr** [absinthe-graphql/absinthe_plug#198]
I'm currently using Phoenix 1.4 and Ecto 3 which defaults to Jason as primary JSON parser. Is there any way for me to set a custom JSON parser?

**Comment by benwilson512** [comment]
Hey @ffimnsr. Configuring the json codec is documented here: https://hexdocs.pm/absinthe_plug/Absinthe.Plug.html#t:opts/0

**Comment by ffimnsr** [comment]
Oh sorry yeah, didn't read that part. Thanks
