### ISSUE TITLE
Something Askew with Router Config

### ISSUE THREAD

**Issue by jherdman** [absinthe-graphql/absinthe_plug#202]
Hi! I'm new to Absinthe, and I'm following along with https://hexdocs.pm/absinthe/our-first-query.html (the steps appear to be congruent with that of the README). I'm running into this error:

```
function BlogWeb.Absinthe.Plug.GraphiQL.init/1 is undefined (module BlogWeb.Absinthe.Plug.GraphiQL is not available)
```

I'm at a complete loss as to what's happening.

Repo: https://github.com/jherdman/blog_ex
Elixir: 1.8.1.

Other stats:

Erlang/OTP 21 [erts-10.3.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

IEx 1.8.1 (compiled with Erlang/OTP 21)

**Comment by jherdman** [comment]
Additionally, if I `iex -S mix` I can see that `Absinthe.Plug` and the corresponding `GraphiQL` modules DO exist.

**Comment by benwilson512** [comment]
Hey @jherdman your issue is that https://github.com/jherdman/blog_ex/blob/master/lib/blog_web/router.ex#L13 should just be `scope "/api" do` not `scope "/api", BlogWeb do`.  The latter prefixes the modules inside the do block with BlogWeb.

**Comment by jherdman** [comment]
D'oh! My many thanks for your speedy reply. <3
