### ISSUE TITLE
Phoenix.ConnTest.get/3 breaks on queries with compiled documents discovery

### ISSUE THREAD

**Issue by dwebster17** [absinthe-graphql/absinthe_plug#205]
I am currently testing compiled queries in Absinthe with `Phoenix.ConnTest.post/3`. When no query document is sent, `Plug.Adapters.Test.Conn` will [add](https://github.com/elixir-plug/plug/blob/master/lib/plug/adapters/test/conn.ex#L155) `--plug_conn_test--` to the request body (with a header of `{"content-type", "multipart/mixed; boundary=plug_conn_test"}`)

In my test case, I have:
```elixir
params = %{variables: %{"id" => thing.uuid}, action: "name_of_compiled_query"}

response =
  conn
  |> post(@graphql_path, params)
  |> json_response(200)
```

which yields the result:

```elixir
%{
  "errors" => [
    %{
      "locations" => [%{"column" => 0, "line" => 1}],
      "message" => "illegal: --"
    }
  ]
}
```

This happens because, when `Absinthe.Plug.DocumentProvider.Default` comes before the compiled document provider, it [pattern matches](https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/document_provider/default.ex#L39-L40) for any non-nil document. This issue is fixed by putting `MyApp.Schema.Documents.Compiled` first. If this is expected behavior, it would be very helpful to make that clear in the documentation.

One possible solution - if `body` is used as the [default document](https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/request/query.ex#L132) when a `query` parameter is not provided, content-type boundaries should be taken into account. I assume that `Absinthe.Plug.DocumentProvider.Default.process/2` was intentionally meant to match non-nil values, so changing that does not seem desireable.

If this is expected behavior, and the default document provider should go last, it would be helpful to explain this in the documentation.

Versions:

* absinthe 1.4.14
* absinthe_ecto 0.1.3
* absinthe_plug 1.4.6

 Edit: this issue also may be more appropriate for the [plug](https://github.com/elixir-plug/plug) repo

**Comment by maartenvanvliet** [comment]
We use compiled documents and indeed the compiled document provider comes before the `Absinthe.Plug.DocumentProvider.Default`. This is expected behaviour afaik. 

Maybe you could file a PR to make this more clear in the docs.

**Comment by binaryseed** [comment]
I added a quick documentation note to address this ordering issue: https://github.com/absinthe-graphql/absinthe_plug/commit/1afbcf245298141c9d27712d993d4146af112736

Thanks!
