### ISSUE TITLE
Log filtering

### ISSUE THREAD

**Issue by benwilson512** [absinthe-graphql/absinthe_plug#21]
Sensitive parameters such as `password` should be filtered from the logs. This works easily with variables, I'm not so sure how it would work with logging the schema document itself.

**Comment by tlvenn** [comment]
Could we leverage the new Meta API to mark a given field as sensitive so that it's filtered out ?

**Comment by tlvenn** [comment]
or rather a specific absinthe macro that flags the field

**Comment by bruce** [comment]
Variable filtering is supported in 1.3 (I think this is best handled at that level, as it directly addresses inputs).
