### ISSUE TITLE
GraphiQL Data Explorer

### ISSUE THREAD

**Issue by rageofflames** [absinthe-graphql/absinthe_plug#211]
Hey there,

Wondering if you are thinking about supporting this query building functionally many are now adopting for GraphiQL, the Data Explorer.

![](https://user-images.githubusercontent.com/476818/51567716-c00dfa00-1e4c-11e9-88f7-6d78b244d534.gif)

We found it to be very useful

**Comment by benwilson512** [comment]
Hi @rageofflames, this is something we think people should build as an external library that depends on absinthe plug. In fact, in future versions of Absinthe.Plug we will probably extract the existing graphiql UIs into their own packages.

**Comment by rageofflames** [comment]
Makes sense 👍

**Comment by xenophilicibex** [comment]
I also would like to use the GraphQL Data Explorer, any ideas on how to build on top of Absinthe Plug to support this?

**Comment by henry-hz** [comment]
@rageofflames  try this: https://github.com/prisma-labs/graphql-playground
you can download the .deb file [here](https://www.electronjs.org/apps/graphql-playground)
