### ISSUE TITLE
Dialyzer warning on `forward` in Phoenix 1.4.7

### ISSUE THREAD

**Issue by barthez** [absinthe-graphql/absinthe_plug#223]
Hello,

I have found out that [one commit](https://github.com/phoenixframework/phoenix/commit/b10fb7dc33a198595872b783cbbf90f1daee91ba) in Phoenix 1.4.7 release introduces the warning to `forward` call with `Absinthe.Plug` (it doesn't do this for `Absinthe.Plug.GraphiQL`.

The warning itself: 
```
router.ex:76:unmatched_return
The expression produces a value of type:

%{
  :adapter => _,
  :before_send => _,
  :content_type => _,
  :context => _,
  :document_providers => _,
  :json_codec => _,
  :log_level => _,
  :no_query_message => _,
  :pipeline => _,
  :pubsub => _,
  :raw_options => Keyword.t(),
  :schema_mod => atom(),
  :serializer => _
}

but this value is unmatched.
```

Related `router.ex` code looks like:

```elixir
  scope "/graphql" do
    pipe_through :graphql

    forward "/", Absinthe.Plug,
      schema: Graphql.Schema,
      json_codec: Jason,
      before_send: {NewRelic.Absinthe, :set_transaction_name}
  end
```

I'm not sure if it is Phoenix fault or this lib. If you find it irrelevant please close the issue.

Looking forward for any hints how to fix it.

Best!

**Comment by binaryseed** [comment]
Closing this for now, if you are still finding this with the latest versions of the libraries, feel free to post more details and maybe a way to reproduce. Thanks!

**Comment by barthez** [comment]
Hey,

Yes, I'm still experiencing this error on the latest versions (phoenix: 1.4.17, absinthe 1.5.3, absinthe_plug: 1.5.0). I have managed to reproduce it on a fresh phoenix project:

mix.exs:
```elixir
  def project do
    [
      ...,
      dialyzer: [
        plt_add_apps: [:ex_unit, :mix],
        flags: [
          :error_handling,
          :race_conditions,
          :underspecs,
          :unmatched_returns
        ]
      ]
    ]
  end

...

  defp deps do
    [
      ...,
      {:absinthe, "~> 1.5"},
      {:absinthe_plug, "~> 1.5"},
      {:dialyxir, "~> 1.0", only: [:dev], runtime: false}
    ]
  end
```

lib/my_schema.ex: 
```elixir
defmodule MySchema do
  use Absinthe.Schema

  query do
    field :test, :string do
      resolve fn _, _ ->
        {:ok, "ok"}
      end
    end
  end
end
```

router.ex:
```elixir
...

  forward "/graphql", Absinthe.Plug,
    schema: MySchema,
    json_codec: Jason

  forward "/playground", Absinthe.Plug.GraphiQL, schema: MySchema
...
```

The dialyzer warning is gone whenever I remove the second `forward` macro call.

**Comment by mohamed-kholfa** [comment]
as a workaround for now we can use `dialyzer.ignore-warnings` and add `lib/my_project_web/router.ex:61`
