### ISSUE TITLE
Add GraphQL support for multipart form requests

### ISSUE THREAD

**Issue by Stanislav-Lapata** [absinthe-graphql/absinthe_plug#226]
Hello. Are you planning to support this [specification](https://github.com/jaydenseric/graphql-multipart-request-spec#graphql-multipart-request-specification)?
All Apollo clients already [support](https://github.com/jaydenseric/graphql-multipart-request-spec#client) this specification.

**Comment by benwilson512** [comment]
There is not unless the official GraphQL spec picks it. You can read my objects to this specific proposal here: https://github.com/jaydenseric/graphql-multipart-request-spec/issues/4

More importantly though, if you _do_ want to use this specification, I don't think Absinthe.Plug needs to handle it first class. You could write a plug that handles this ahead of time, and transforms the request into something that Absinthe.Plug expects.
