### ISSUE TITLE
Raise compile error if inconsistency in options

### ISSUE THREAD

**Issue by thojanssens** [absinthe-graphql/absinthe_plug#229]
If options for the GraphiQL plug are the following:

```
interface: :simple,
default_headers: {__MODULE__, :graphiql_headers}
```

`default_headers` are ignored, because (as docs mention) it will only work if the interface is advanced.

Maybe we can throw an error when we see an inconsistency in the options? This can be done at compile time I guess.

**Comment by benwilson512** [comment]
hi @thojanssens I think the plan here is to actually extract each of the GraphiQL interfaces into their own plug, and perhaps even their own hex packages. This will, amongst other things, simplify these kinds of checks.
