### ISSUE TITLE
is not a valid Absinthe.Schema with wrapped plugs in 1.5.1

### ISSUE THREAD

**Issue by dfalling** [absinthe-graphql/absinthe_plug#238]
I've wrapped the Absinthe.Graphiql.Plug so I can forward to it twice... Once with authentication, and another time for unauthenticated introspection queries:
```elixir
defmodule IdoWeb.GraphQL.Introspection do
  @moduledoc """
  Wrapper around GraphiQL plug so we can re-use it in another route.
  (Phoenix prohibits forwarding to the same plug more than once)
  https://github.com/graphql-elixir/plug_graphql/issues/7
  https://github.com/phoenixframework/phoenix/pull/1419
  """
  use Plug.Builder

  plug(Absinthe.Plug.GraphiQL)
end
```

```elixir
  # router.ex

  # GraphQL
  scope "/" do
    pipe_through([:api, :protected])

    forward("/graphql", Absinthe.Plug)

    if Mix.env() == :dev do
      forward("/graphiql", Absinthe.Plug.GraphiQL)
    end
  end

  if Mix.env() == :dev do
    # forward("/introspection", IdoWeb.GraphQL.Introspection)
  end
```

This worked great until 1.5.1, but now I'm getting this:
```
== Compilation error in file lib/ido_web/graphql_introspection_plug.ex ==
** (ArgumentError) IdoWeb.Schema is not a valid `Absinthe.Schema`
```

The change in 1.5.1 is the addition of this check:

```elixir
  defp valid_schema_module?(module) do
    is_atom(module) &&
      Code.ensure_loaded?(module) &&
      Absinthe.Schema in Keyword.get(module.__info__(:attributes), :behaviour, [])
  end
```

I don't get this error with `forward("/graphql", Absinthe.Plug)` or `forward("/graphiql", Absinthe.Plug.GraphiQL)`.  Is there some other change I need to make for 1.5.1 for this wrapping to continue working?

**Comment by benwilson512** [comment]
Hey @dfalling the correct way to wrap a plug is to delegate to the plug module.

```
defmodule IdoWeb.GraphQL.Introspection do
  @behaviour Plug
  defdelegate init(opts), to: Absinthe.Plug.GraphiQL
  defdelegate call(conn, opts), to: Absinthe.Plug.GraphiQL
end
```

I'm not 100% sure how your version is giving you your error though, are you eliding the `schema` option from your code samples here?

**Comment by dfalling** [comment]
Ah, thanks!  Switching to `defdelegate` fixed it.

I was excluding the schema from my plugs- it's configured in my config.exs and from the error message I could see it was at least getting picked up.
