### ISSUE TITLE
Race Condition Related to Code Compilation

### ISSUE THREAD

**Issue by wjdix** [absinthe-graphql/absinthe_plug#239]
I believe that https://github.com/absinthe-graphql/absinthe_plug/commit/389a8442e5b1b0a77a1d7a27a8f893eb894a7559 introduced a regression between `1.5.0` and `1.5.1`. This validity check causes schemas to be invalid if they have not yet been compiled. This is because `Code.ensure_loaded?` will return false when the schema module has not been compiled. 

I was able to verify this in our codebase by inserting a sleep into `Absinthe.Plug.valid_schema_module?/1`. With the sleep inserted, our schema would be vaildated successfully. We were able to work around this problem by explicitly requiring the schema module in our Plug Router. 

`valid_schema_module?/1` is called within `Absinthe.Plug.init/1` which is in turn called here https://github.com/elixir-plug/plug/blob/master/lib/plug/router.ex#L554 which occurs during macro expansion.

I believe this method will still work as expected without the call to `Code.ensure_loaded?`. However, if retaining that call is desirable, it might be worth improving the error message here and documenting that the schema module should be explicitly required before using `Absinthe.Plug`

**Comment by benwilson512** [comment]
Hey @wjdix yeah our various efforts to detect if it's the right module at compile time have always run into issues, I think we need to probably move the check to run time.

**Comment by wjdix** [comment]
I think `Code.ensure_compiled/1` could work for this purpose, but it would cause the initialization to hang until either the schema module was compiled or _all_ modules were compiled. That might be desirable?

**Comment by benwilson512** [comment]
@wjdix We could, but it also can increase the amount of compile time linking that can occur. I'll test it out locally and see.

**Comment by binaryseed** [comment]
I think for this check, we really just care to validate that it's "correct" in that it's actually a schema module, not something else. That does seem to imply that we need the module to actually be compiled.

**Comment by binaryseed** [comment]
Here's a PR that switches to `Code.ensure_compiled`: https://github.com/absinthe-graphql/absinthe_plug/pull/240

What do you think @benwilson512 ?
