### ISSUE TITLE
Dynamically generated max complexity

### ISSUE THREAD

**Issue by paulstatezny** [absinthe-graphql/absinthe_plug#241]
Hello! 👋 First of all, thank you for Absinthe and `Absinthe.Plug`!

I'm wondering if the maintainers would be open to the addition of a feature to dynamically determine the max complexity per query. I'd like to be able to say something like, "User X made a query, they have Y complexity allowance left, will I allow them to make this query?"

Of course this doesn't match the primary use case. 😄 

Whereas the current API looks like this:

```elixir
plug Absinthe.Plug,
  schema: MyAppWeb.Schema,
  analyze_complexity: true,
  max_complexity: 50
```

I would like to propose expanding the API to support this as well:

```elixir
plug Absinthe.Plug,
  schema: MyAppWeb.Schema,
  analyze_complexity: true,
  max_complexity: &MyModule.max_complexity/1
```

Where `&MyModule.max_complexity/1` is a function that is given the context and query and returns back an integer.

Thank you for considering! I would be glad to whip up a PR if you're open to this. Cheers!

**Comment by binaryseed** [comment]
We do something similar to this with a custom plug that delegates to `Absinthe.Plug`, but it's an interesting idea. What do you think @benwilson512 ?

**Comment by benwilson512** [comment]
I think we should allow this to be set via `Absinthe.put_options` in a higher up plug, it generalizes a lot better. Currently we enable this with a few options https://github.com/absinthe-graphql/absinthe_plug/blob/v1.5.2/lib/absinthe/plug.ex#L301 but we should generalize this to all of the options.

**Comment by benwilson512** [comment]
In the short term @paulstatezny you can wrap Absinthe.Plug:

```
defmodule MyAbsinthePlug do

  defdelegate init(opts), to: Absinthe.Plug

  def call(conn, opts) do
    complexity = complexity_for_current_user(conn)
    opts = Map.put(opts, :complexity, complexity)

    Absinthe.Plug.call(conn, opts)
  end
end
```

**Comment by paulstatezny** [comment]
Thanks for such a quick and helpful reply! ❤️

**Comment by binaryseed** [comment]
Opened a PR for this https://github.com/absinthe-graphql/absinthe_plug/pull/243
