### ISSUE TITLE
upgrade from 1.5.3 to 1.5.4 breaks default pub sub option

### ISSUE THREAD

**Issue by woylie** [absinthe-graphql/absinthe_plug#247]
The upgrade from 1.5.3 to 1.5.4 broke our application. We didn't set the `pubsub` option explicitly, but relied on the default `conn.private[:phoenix_endpoint]`. After the upgrade, this default apparently gets overwritten by the `update_config` function. We noticed because subscription triggers still worked when pushing mutations via a socket, but they didn't work anymore when sending a mutation via HTTP.

**Comment by benwilson512** [comment]
Hi @woylie, are you setting `pubsub` explicitly in update_config? It shouldn't be overriding it with `nil`, can you elaborate?

**Comment by woylie** [comment]
We're not using `update_config` at all.

**Comment by binaryseed** [comment]
Here's the PR that recently changed this logic: https://github.com/absinthe-graphql/absinthe_plug/pull/243

Though quickly looking through it I don't see anything obviously wrong...

**Comment by benwilson512** [comment]
Right, @woylie how / where would update_config override things? How are you determining that pubsub is being unset?

**Comment by woylie** [comment]
I'm sorry, I didn't have any time to investigate this any further. I don't actually know that `pubsub` is being unset, that was my assumption based on:

- Upgrading from 1.5.3 to 1.5.4 causes mutations sent via HTTP not triggering any subscription messages, while mutations via socket still trigger them as expected.
- This problem can be reliably fixed/reproduced by down/upgrading between 1.5.3 and 1.5.4. No other changes are necessary, no other dependency versions are changed in `mix.lock`.
- The only change between 1.5.3 and 1.5.4 is in the `update_config` function.

**Comment by woylie** [comment]
This happens with absinthe 1.5.5 and absinthe_phoenix 2.0.0.

**Comment by benwilson512** [comment]
So the actual observed behavior is this:
> mutations sent via HTTP not triggering any subscription messages, while mutations via socket still trigger them as expected.

**Comment by woylie** [comment]
Yes. Sorry for not being clearer in the first description.

**Comment by binaryseed** [comment]
We figured it out, here's a fix: https://github.com/absinthe-graphql/absinthe_plug/pull/249

**Comment by woylie** [comment]
Great, thanks!
