### ISSUE TITLE
Allow using a struct as the absinthe context

### ISSUE THREAD

**Issue by coryodaniel** [absinthe-graphql/absinthe_plug#258]
My application has a few different authentication contexts. I tried using a struct instead of a map when assigning a context to Abinsthe.Plug, but it results in an error.

Is there any reason why structs shouldn't be a valid value? I wouldn't mind making a PR if it makes sense for the project.

```
       (elixir 1.11.4) lib/access.ex:286: Access.get/3
       (absinthe_plug 1.5.5) lib/absinthe/plug.ex:332: Absinthe.Plug.update_config/3
       (absinthe_plug 1.5.5) lib/absinthe/plug.ex:289: Absinthe.Plug.call/2
       (phoenix 1.5.8) lib/phoenix/router/route.ex:41: Phoenix.Router.Route.call/2
       (phoenix 1.5.8) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
       (massdriver 0.1.0) lib/massdriver_web/endpoint.ex:1: MassdriverWeb.Endpoint.plug_builder_call/2
       (massdriver 0.1.0) lib/massdriver_web/endpoint.ex:1: MassdriverWeb.Endpoint.call/2
       (phoenix 1.5.8) lib/phoenix/test/conn_test.ex:225: Phoenix.ConnTest.dispatch/5
       test/massdriver_web/schema_test.exs:103: (test)
```

**Comment by benwilson512** [comment]
Hi @coryodaniel . This is an issue because your specific struct does not implement the Access behavior. Absinthe is not explicitly disallowing it, but it does require that it behaves as a map.

**Comment by coryodaniel** [comment]
Thanks for the quick reply!

I get that it’s because the access behavior isn’t implemented, I guess my question is, if I sent a PR to use Map functions instead of using the access behavior so structs would be supported, would that be a welcome feature? Or do you prefer users impl the access behavior should they need it.

**Comment by benwilson512** [comment]
@coryodaniel I think a PR that used map functions is fine, BUT we need to make sure that a `nil` context is still supported for backwards compatibility reasons.

In theory this could break compatibility for anyone using a novel KV struct that implemented its own access behavior but the use of access wasn't really intended to support that anyway.
