### ISSUE TITLE
GraphiQL "proxies" graphql endpoint

### ISSUE THREAD

**Issue by juulSme** [absinthe-graphql/absinthe_plug#261]
In my router I have something like this:

```elixir
pipeline :graphql do
  plug :auth
end

scope "/api" do
  pipe_through :graphql
  forward "/graphql", Absinthe.Plug, ...
end

forward "/explorer", Absinthe.Plug.GraphiQL, ...
```

It seems, however, that /explorer is now also a graphql endpoint. I can introspect the schema at that path, and can also send queries to it, and those queries are run by my resolvers, *without* passing through my plug `:auth`, effectively bypassing my authentication plugs. This seems to be unexpected behaviour to me. It can be fixed by simply putting the `forward "/explorer"` in the same scope so that it is piped through the same plugs, but I can't tell from the docs that this is advisable. Nor is it explicit that `Absinthe.Plug.GraphiQL` exhibits this "proxying" behavior.

**Comment by juulSme** [comment]
Or maybe I missed something in the docs ;)

**Comment by benwilson512** [comment]
This is intentional, the GraphiQL plug is intended to be self sufficient.

**Comment by dagumak** [comment]
> This is intentional, the GraphiQL plug is intended to be self sufficient.

Do you have suggestions for how we can test authentication middleware if this is intentional? It would seem more natural to have a GUI mounted in one URL and then allow a configuration POST to your API endpoint so then you can develop/test against all the plugs in `pipe_through`.
