### ISSUE TITLE
Possible to access context during subscription config?

### ISSUE THREAD

**Issue by artificial-mwatson** [absinthe-graphql/absinthe_plug#263]
Some customers, when they submit a subscribe document want us to send them the "current" version of what they're subscribing to.  The problem is that doing so requires access to the context which contains information about the user, their authentication, and key values that are needed to be able to send them the correct data.

The subscription's config macro doesn't seem to give us access to the context that the plug inserted for that user.  Is it possible to access the context from inside the config so we can trigger the proper channel publish operation?

We're migrating from Apollo, and this was something they had in Apollo that we'd like to preserve.

Thanks.

**Comment by benwilson512** [comment]
Hi, the context is indeed available, please see the example shown here: https://hexdocs.pm/absinthe/Absinthe.Schema.Notation.html#config/1-examples

**Comment by artificial-mwatson** [comment]
Many thanks, @benwilson512!

**Comment by artificial-mwatson** [comment]
Since subscription goes over a Phoenix.Socket, that doesn't go through the Plug pipeline, near as I can tell, and don't work on conns.  So how can I get something into the absinthe context when using a socket?

**Comment by benwilson512** [comment]
Hi @artificial-mwatson please use the slack for questions not the issue tracker. This is also covered in the docs https://hexdocs.pm/absinthe_phoenix/Absinthe.Phoenix.Socket.html#content
