### ISSUE TITLE
No query document supplied error

### ISSUE THREAD

**Issue by DaveElGhoul** [absinthe-graphql/absinthe_plug#271]
I have a weird issue where the no query document supplied error pops up.
Whenever I run the server locally or access the remote one, on one laptop everything works fine, but on the other, both local and remote servers return No Query Document supplied error with 400 status code...

Both laptops are macbook pros.
I also tried Safari and Chrome on the faulty one

**Comment by benwilson512** [comment]
Hi @DaveElGhoul please use the forums or other Elixir chat locations for debugging help. When you ask there please be sure to provide copies of the code you're running and how you're making requests.
