### ISSUE TITLE
Igniter Upload Setup

### ISSUE THREAD

**Issue by maennchen** [absinthe-graphql/absinthe_plug#291]
Continuation of ash-project/ash#1337

## Setup Required

* Add `import_types Absinthe.Plug.Types` to schema
* Add `Absinthe.Plug.Parser` to `Plug.Parsers` plug in endpoint

**Comment by benwilson512** [comment]
Hi @maennchen that is a moderately long discussion, can you distill that down into what is being asked of AbsinthePlug?

**Comment by maennchen** [comment]
Oh, I opened this ticket in the wrong repo, sorry @benwilson512

**Comment by maennchen** [comment]
Should've gone here: https://github.com/ash-project/ash_graphql/issues/201
