### ISSUE TITLE
Update for GraphiQL changes

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe_plug#37]
@tlvenn Do we need to update the "advanced" GraphiQL (now GraphiQL Workspace), based on your conversation here: https://github.com/OlegIlyenko/graphql-toolbox/issues/3 ?

**Comment by bruce** [comment]
Also, I want to make sure that:

- [ ] Credit is given to Oleg, et al, for the GraphiQL inclusion in the the README
- [ ] Any necessary license is included

**Comment by tlvenn** [comment]
Ya I am working on it with Oleg, there are a few issues that we need to solve before we can publish graphiql-workspace with jsdelivr and use it with Absinthe.

**Comment by bruce** [comment]
@tlvenn Any update on this? I think we need to freshen up the version of graphiql used; is there anything we need to do here? I saw this: https://github.com/OlegIlyenko/graphql-toolbox/issues/10

**Comment by tlvenn** [comment]
Hi @bruce, sorry meant to follow up on that sooner. I had open a PR to build the minify version that can be served using jsdelivr and then that we can use:
>https://github.com/OlegIlyenko/graphiql-workspace/pull/2

There are issues raised by Oleg and I will follow up with him this coming week to fix them.

**Comment by tlvenn** [comment]
The PR has been merged, i have created 2 small PRs to update the project to the latest graphiql / graphql and add configurable headers. Should be relatively quick to merge them and then publish a new version to npm.

The issue tracking this is: https://github.com/OlegIlyenko/graphiql-workspace/issues/1

So hopefully we can expect to update the version we are using in the coming days.
