### ISSUE TITLE
Return arbitrary status codes

### ISSUE THREAD

**Issue by clessg** [absinthe-graphql/absinthe_plug#45]
Is it possible to return arbitrary HTTP status codes, e.g. a 401 Unauthorized when a particular field requires authentication?

I'm currently using a custom `private` function to wrap resolver functions, which returns `{:error, "Must be logged in"}` if the user is not authenticated:

```elixir
query do
  field :posts, list_of(:post) do
    resolve private &App.PostResolver.all/2
  end
end

defp private(fun) do
  fn args, %{context: context} = info ->
    case context do
      %{current_user: user} when not is_nil(user) -> fun.(args, info)
      _ -> {:error, "Must be logged in"}
    end
  end
end
```

This results in a 200 status code even when an error is returned, which complicates error handling. It would be nice if we could return, e.g. `{:error, message: "...", plug_status: 401}`.

You *can* use Plug's exception protocol for this, but it feels kind of wrong:

```elixir
case context do
  %{current_user: user} when not is_nil(user) -> fun.(args, info)
  _ -> raise App.Unauthorized
end

defmodule App.Unauthorized do
  defexception [message: "Must be logged in", plug_status: 401]
end
```

**Comment by benwilson512** [comment]
This is intentionally not supported. GraphQL does not use HTTP status codes for semantic value. If you want to do authorization in the plug pipeline prior to Absinthe.Plug we cover how to do so here: http://absinthe-graphql.org/guides/context-and-authentication/

**Comment by benwilson512** [comment]
You may want to check out master where we support returning more complex error messages. So you could return something like:

```
{:error, %{message: "Unauthorized", status: 401}}
```

**Comment by clessg** [comment]
Thanks, @benwilson512! The only problem with doing authorization prior to Absinthe.Plug is that it's all-or-nothing - you can't whitelist/blacklist specific fields.

It makes sense that GraphQL doesn't use HTTP status codes, though. If one field were successful (200) and another unsuccessful (401), what would the server return? The complex error messages make more sense - thanks for pointing me in the right direction.

**Comment by benwilson512** [comment]
>  If one field were successful (200) and another unsuccessful (401), what would the server return?

Yup yeah this is the core issue. Hopefully the complex error messages will suite your needs!

**Comment by dagumak** [comment]
> This is intentionally not supported. GraphQL does not use HTTP status codes for semantic value. If you want to do authorization in the plug pipeline prior to Absinthe.Plug we cover how to do so here: http://absinthe-graphql.org/guides/context-and-authentication/

Updated link for others: https://github.com/absinthe-graphql/absinthe/blob/master/guides/context-and-authentication.md
