### ISSUE TITLE
Should Absinthe.Plug.GraphiQL serve the API requests, too?

### ISSUE THREAD

**Issue by leonid-shevtsov** [absinthe-graphql/absinthe_plug#66]
I'm a little confused on how the GraphiQL feature is intended.

I assumed it's just to serve a separate JS app for GraphiQL. Thus, we had this configuration in our router:

```
  # The API endpoint
  scope "/api/v1" do
    pipe_through :api
    forward "/graphql", Absinthe.Plug, schema: Myapp.Schema
  end

  # The GraphiQL app
  if Mix.env == :dev do
    forward "/graphiql", Absinthe.Plug.GraphiQL, schema: Myapp.Schema
  end
```

The problem we have with this setup is that `/graphiql` _also serves the GraphQL API_. Two other people tried using the GraphiQL app, entering its own URL - `/graphiql` - instead of the API URL - `/api/v1/graphql`. Surprisingly for me, it worked. Except since the second endpoint is not piped through API, the GraphQL resolvers didn't get receive proper context and the API failed in various subtle and not so subtle ways. This was fixed by explaining the guys they should use the correct API endpoint.

Please explain, are we doing something idiomatically wrong?

**Comment by benwilson512** [comment]
This is the expected behaviour yes, the GraphiQL plug is 100% self sufficient.
