### ISSUE TITLE
Absinthe dependency is too strict on v1.3 branch.

### ISSUE THREAD

**Issue by matthewlehner** [absinthe-graphql/absinthe_plug#67]
Absinthe dependency seems like it should be relaxed to use `~> 1.3.0-beta.0` to allow any beta release to work with `absinth_plug`.

I'm happy to send a PR if it's helpful. Work is ready at:
matthewlehner/absinthe_plug@f334567d3f5c4ce62a8ccde1261212643f6661d9

**Comment by benwilson512** [comment]
That would be perfect, thanks!
