### ISSUE TITLE
Add Prettify button

### ISSUE THREAD

**Issue by dplummer** [absinthe-graphql/absinthe_plug#70]
In previous versions of absinthe_plug, we had a sweet prettify button:

![screen shot 2017-04-10 at 8 41 35 am](https://cloud.githubusercontent.com/assets/98884/24870070/fd2cf04c-1dc9-11e7-835e-dab244c80904.png)

But as of 3cc48893 we do not :(

<img width="325" alt="screen shot 2017-04-10 at 8 45 27 am" src="https://cloud.githubusercontent.com/assets/98884/24870100/11569118-1dca-11e7-8747-5594ca3f1c4e.png">

I always found that to be super helpful, and would like to add it back in. It worked well where it was before, right next to the Run button above the query input.

The loss may be related to [v0.9.3 of GraphiQL](https://github.com/graphql/graphiql/commit/7e1c95ab6e8606609271502c3e49650451725e9a) they removed the hardcoded prettify button. Perhaps the graphiql-workspace project didn't get the memo.

**Comment by bruce** [comment]
Thanks for the detail here. We don't plan on adding and maintaining customizations to the JS bits in the plug itself, as we'd like to track the official projects without dealing with merge issues, etc. We would be open to supporting options to allow custom JS file(s) to be loaded (either as a replacement or in addition and hosted both remotely and from, eg `priv/static`). 

We're pretty busy with wrapping up the 1.3 release, etc, so if that's something you'd like to pursue and you have the time to look at implementation, it would be done a lot quicker.

(The cheap and dirty option here, of course, for you personally is just copying the plug and customizing locally.)

**Comment by dplummer** [comment]
+1 for avoiding merge conflicts :)

For the moment I've gone back to 1.2.4. If I figure out how to add the button back at all, I'll post back here.

Thanks for all your hard work on absinthe, it's awesome!

**Comment by bruce** [comment]
Sure thing :-) Reopen here down the road (or start a PR) when the time comes.
