### ISSUE TITLE
GraphiQL doesn't show (1.3.0-rc.0)

### ISSUE THREAD

**Issue by avitex** [absinthe-graphql/absinthe_plug#73]
[`select_mode` ](https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/graphiql.ex#L135) is expecting a `document: nil` when it's given a list containing queries.

I patched it on my side with:
```
defp select_mode(%{queries: [%Absinthe.Plug.Request.Query{document: nil}]}), do: :start_interface
````

I can create a PR if you like.

**Comment by bruce** [comment]
@avitex Thanks for catching this. If you can create a PR, that would be really helpful. We'll look into doing a release in the morning US time.

**Comment by bruce** [comment]
(Oh, nevermind -- I see you already did; thanks!)
