### ISSUE TITLE
Batching and upload

### ISSUE THREAD

**Issue by yury-dymov** [absinthe-graphql/absinthe_plug#81]
Hi guys, first of all, thank you for the great library!

I am not sure if it is an issue rather than a question but I would like to be able to upload files and use batching at the same time.

I was playing around with CURL to build the working request first and then to implement a plugin for the apollo-client library to make things work.

For the single request everything works great
```
curl -X POST \
-F query="mutation createPost(\$text: String, \$image: String){createPost(image: \$image, text:\$text, locked: false) { id }}" \
-F operationName="createPost" \
-F variables="{\"text\":\"hello\",\"image\":\"me_jpg\"}" \
-F me_jpg=@me.jpg \
localhost:4000/graphql
```

The question is, how can I convert this single request in a batched one?

Thank you in advance!

**Comment by benwilson512** [comment]
This is now handled on master: https://github.com/absinthe-graphql/absinthe_plug/blob/master/test/lib/absinthe/plug/transport_batching_test.exs#L331-L355

A release will happen soon.
