### ISSUE TITLE
Support for formats other than JSON

### ISSUE THREAD

**Issue by idi-ot** [absinthe-graphql/absinthe_plug#82]
Hi!

With GraphQL being data format agnostic and all it might be nice to be able to use `absinthe_plug` with a custom serializer like [msgpax](https://github.com/lexmag/msgpax) or maybe just `:erlang.term_to_binary`
```elixir
plug Absinthe.Plug,
  schema: MyApp.Schema,
  serializer: MyApp.Serializer
```
where `MyApp.Serializer` would implement callbacks similar to those for phoenix channels.

**Comment by bruce** [comment]
@idi-ot I think this is a wonderful idea. It would likely involve reworking the `:json_codec` option, and would need to support similar configuration options; if you'd like to take a crack at it, we'd be happy to review and give pointers. The `:json_codec` option just needs to be left in to be backwards-compatible.

**Comment by idi-ot** [comment]
Thanks, I will be able to start working on it sometime next week (or maybe the week after that).
