### ISSUE TITLE
Invalid JS in graphiql-workspace CDN

### ISSUE THREAD

**Issue by kbredemeier** [absinthe-graphql/absinthe_plug#83]
The graphiql-workspace javascript from the unpkg.com CDN seems to contain invalid javascript. I am geeting an syntax error.

**Comment by benwilson512** [comment]
Everything works fine as is for me, can you elaborate on the error?

**Comment by kbredemeier** [comment]
Yes, on my co-workers machine it works too. Try an anonomys window or clear the cache.

My js console says: `Uncaught SyntaxError: Invalid or unexpected token in graphiql-workspace.min.js:18`

If I copy & paste the script from the cdn in a [syntax checker](http://esprima.org/demo/validate.html) it reports an illegal token in line 18.

The js from the other cdn works though
