### ISSUE TITLE
Use GraphiQL tool offline

### ISSUE THREAD

**Issue by yordis** [absinthe-graphql/absinthe_plug#86]
I notice that all the assets are being pull up from the CDN. Is there any way to add that locally so it can work on offline connections?

There is only one reason I am asking and it's that some countries (Cuba in this case) can't access to the internet 24/7 so use GraphiQL is kind of impossible if it loads from the CDN. Also, working from a place that I can't access to the internet (like airplanes)

Do you have any suggestion in how to fix this? I am thinking that the only way is to download GraphiQL tool and run it locally and do not use this one I guess, but I am wondering if there if we could add offline support.

**Comment by bruce** [comment]
@yordis @benwilson512 and I have talked about this a bit before. Here are my thoughts on how to do this:

- It should be opt-in. If people just pull down the plug, I don't think they expect to get a load of JS as well. By default, it should load the assets from the CDN.
- Opting in should be as simple as running a mix task. Once that's run (and the assets pulled into `priv` or wherever), the plug should load them from that location.
- We should still tie absinthe_plug versions to specific GraphiQL versions (the two types of GraphiQL we support); the mix task should just pull down the "correct" GraphiQL revision that's been defined for the current absinthe_plug version. (We need to be able to test a specific GraphiQL against Absinthe; locking the versions helps us ensure that when we ship a version we're sure the GraphiQL we've "blessed" works. People can always PR version bumps that we can test.)
- However it's done, the approach should work flexibly enough to support other JS + CSS tools too; we'd like to expand past GraphiQL (like GraphQL Voyager, https://github.com/APIs-guru/graphql-voyager)

**Comment by yordis** [comment]
@bruce would be better for use to push these tools out of this package, like an external tooling?

I am working on this https://github.com/straw-hat-llc/graphiql-workspace-app, which I glad you tell me about the versioning so I can adjust it now

**Comment by yordis** [comment]
Look at this https://github.com/OlegIlyenko/graphiql-workspace/issues/17

**Comment by bruce** [comment]
By mix task I just mean a bundled task that can be executed in applications with, eg, `mix absinthe.plug.graphiql.workspace.download`. It knows where to find the field from CDN, puts them in priv, done.

The plugs themselves would just need to know whether their assets are available in priv.

There's no need to require an out-of-band Node.js dependency.

**Comment by yordis** [comment]
@bruce got it! I am confused about the URL to the asset, normally in phoenix that is configured but I never did it without so I have to dig in.

And, when I download the assets I should't just check in the files are there, every single one?!

Requirements
- [ ] Create Mix task that download the assets from the CDN
  - [ ] Use local assets if they exist locally.

**Comment by yordis** [comment]
@bruce we could probably close this one and keep working with #99
