### ISSUE TITLE
Issue loading graphiql

### ISSUE THREAD

**Issue by baldmountain** [absinthe-graphql/absinthe_plug#94]
The graphiql-workspace.min.js at https://unpkg.com/graphiql-workspace@1.0.4/graphiql-workspace.min.js is truncated so graphiql won't load. 

Changing this line: https://github.com/absinthe-graphql/absinthe_plug/blob/master/lib/absinthe/plug/graphiql.ex#L65 to 1.0.3 seems to fix it.

**Comment by duksis** [comment]
this was solved here https://github.com/absinthe-graphql/absinthe_plug/commit/bb3815690cd9b099c325fa7a57db170879b59a54 
@bruce would it be possible to release v1.3.1 + the above commit as v1.3.2 ?
that would make the stable absinthe_plug usable with stable absinthe_ecto

**Comment by benwilson512** [comment]
I think this will just get rolled up in the 1.4 release.
