### ISSUE TITLE
[help] get informations about errors

### ISSUE THREAD

**Issue by gullitmiranda** [absinthe-graphql/absinthe_plug#95]
what is the best way to capture the exception for the stack trace error with `Absinthe.Plug`?
to Plug application I can use this: https://hexdocs.pm/rollbax/using-rollbax-in-plug-based-applications.html#content

put it but this does not capture the information of the absinthe context.

raw send to rollbar: https://gist.github.com/gullitmiranda/822c843393ede374333bd737fff34a51

this raw makes it clear that the exception is not passed to the `Plug.ErrorHandler`

**Comment by benwilson512** [comment]
I'm not sure I understand. Absinthe.Plug doesn't work any differently than any other plug. The context isn't a magic value, it's just one of many maps used by Absinthe. If you want it to be part of the stuff sent to rollbax you'll likely need to manually specify that information prior to running Absinthe.Plug
