### ISSUE TITLE
GraphiQL Offline Support: GraphiQL Workspace missing fonts

### ISSUE THREAD

**Issue by bruce** [absinthe-graphql/absinthe_plug#99]
For @yordis: Some leftover work from #88; assets downloaded for GraphiQL Workspace (the default GraphiQL client displayed by Absinthe.Plug) do not include the icon fonts.

**Comment by bruce** [comment]
This should be checked again after #107.

**Comment by yordis** [comment]
@bruce as long as the CSS files actually use a local path to the fonts we should be fine I guess.

**Comment by avitex** [comment]
Once #124 is merged this can be closed. I've verified that the assets/fonts are downloaded for `simple`, `advanced` and `playground` and that they are used once in the local path successfully.

**Comment by tlvenn** [comment]
Thanks for the fix @avitex !
